name: Deploy to CDN
on:
  push:
    branches:
      - main
    paths:
      - "packages/**"

jobs:
  upload-to-cdn:
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # ratchet:step-security/harden-runner@v2.21.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Upload dependencies to CDN
        uses: nais/deploy/actions/cdn-upload/v2@027a91857992525139798892f2804b0ca21f4af6 # ratchet:nais/deploy/actions/cdn-upload/v2@v2
        with:
          team: okonomi
          source: ./packages
          destination: sokos-shared-dependencies
