name: Deploy to CDN
on:
  push:
    branches:
      - main
    paths:
      - "packages/**"

jobs:
  upload-to-cdn:
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # ratchet:step-security/harden-runner@v2.19.4
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
        with:
          persist-credentials: false

      - name: Upload dependencies to CDN
        uses: nais/deploy/actions/cdn-upload/v2@2d18f050f07b6a007864c6a57070ed915d571beb # ratchet:nais/deploy/actions/cdn-upload/v2@v2
        with:
          team: okonomi
          source: ./packages
          destination: sokos-shared-dependencies
