name: Deploy to CDN
on:
  push:
    branches:
      - main
    paths:
      - "packages/**"

jobs:
  upload-to-cdn:
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10" # ratchet:actions/checkout@v5
        with:
          persist-credentials: false

      - name: Upload dependencies to CDN
        uses: nais/deploy/actions/cdn-upload/v2@ab841e4d99cbb00edd996d3ae39bd4cea6b8e2c2 # ratchet:nais/deploy/actions/cdn-upload/v2@master
        with:
          team: okonomi
          source: ./packages
          destination: sokos-shared-dependencies
